[package]
name = "sigwa-core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
alloy-primitives = { version = "1.1.2", features = ["serde"] }

anyhow = "1.0"

async-trait = { version = "0.1.83" }
